Add-Type -AssemblyName System.Web
$outputPath = "D:\Source\Github\covenas\src\js\localization"

Get-ChildItem $outputPath -Filter *.json | 
Foreach-Object {
    $content = Get-Content $_.FullName
    Write-Output "Processing: " + $_.FullName;
                         
    # Spanish special characters
          
    $escapedContent = $content -replace "Á", "&Aacute;" 
    $escapedContent = $content -replace "É", "&Eacute;" 
    $escapedContent = $content -replace "Í", "&Iacute;" 
    $escapedContent = $content -replace "Ó", "&Oacute;" 
    $escapedContent = $content -replace "Ñ", "&Ntilde;" 
    $escapedContent = $content -replace "Ú", "&Uacute;" 
    $escapedContent = $content -replace "Ü", "&Uuml;" 
    $escapedContent = $content -replace "¡", "&iexcl;" 
    $escapedContent = $content -replace "¿", "&iquest;" 
    $escapedContent = $content -replace "á", "&aacute;" 
    $escapedContent = $content -replace "é", "&eacute;" 
    $escapedContent = $content -replace "í", "&iacute;" 
    $escapedContent = $content -replace "ó", "&oacute;" 
    $escapedContent = $content -replace "ñ", "&ntilde;" 
    $escapedContent = $content -replace "ú", "&uacute;" 
    $escapedContent = $content -replace "ü", "&uuml;" 
    $escapedContent = $content -replace "ª", "&ordf;" 
    $escapedContent = $content -replace "º", "&ordm;"   
    
    # Portugese characters
    $escapedContent = $content -replace "À", "&Agrave;" 
    $escapedContent = $content -replace "Á", "&Aacute;" 
    $escapedContent = $content -replace "Â", "&Acirc;" 
    $escapedContent = $content -replace "Ã", "&Atilde;" 
    $escapedContent = $content -replace "Ç", "&Ccedil;" 
    $escapedContent = $content -replace "È", "&Egrave;" 
    $escapedContent = $content -replace "É", "&Eacute;" 
    $escapedContent = $content -replace "Ê", "&Ecirc;" 
    $escapedContent = $content -replace "Ì", "&Igrave;" 
    $escapedContent = $content -replace "Í", "&Iacute;" 
    $escapedContent = $content -replace "Ï", "&Iuml;" 
    $escapedContent = $content -replace "Ò", "&Ograve;" 
    $escapedContent = $content -replace "Ó", "&Oacute;" 
    $escapedContent = $content -replace "Õ", "&Otilde;" 
    $escapedContent = $content -replace "Ù", "&Ugrave;" 
    $escapedContent = $content -replace "Ú", "&Uacute;" 
    $escapedContent = $content -replace "Ü", "&Uuml;" 
    $escapedContent = $content -replace "à", "&agrave;" 
    $escapedContent = $content -replace "á", "&aacute;" 
    $escapedContent = $content -replace "â", "&acirc;" 
    $escapedContent = $content -replace "ã", "&atilde;" 
    $escapedContent = $content -replace "ç", "&ccedil;" 
    $escapedContent = $content -replace "è", "&egrave;" 
    $escapedContent = $content -replace "é", "&eacute;" 
    $escapedContent = $content -replace "ê", "&ecirc;" 
    $escapedContent = $content -replace "ì", "&igrave;" 
    $escapedContent = $content -replace "í", "&iacute;" 
    $escapedContent = $content -replace "ï", "&iuml;" 
    $escapedContent = $content -replace "ò", "&ograve;" 
    $escapedContent = $content -replace "ó", "&oacute;" 
    $escapedContent = $content -replace "õ", "&otilde;" 
    $escapedContent = $content -replace "ù", "&ugrave;" 
    $escapedContent = $content -replace "ú", "&uacute;" 
    $escapedContent = $content -replace "ü", "&uuml;" 
    $escapedContent = $content -replace "ª", "&ordf;" 
    $escapedContent = $content -replace "º", "&ordm;" 
    
    # French characters  
    $escapedContent = $content -replace "À", "&Agrave;" 
    $escapedContent = $content -replace "Â", "&Acirc;" 
    $escapedContent = $content -replace "Ç", "&Ccedil;" 
    $escapedContent = $content -replace "È", "&Egrave;" 
    $escapedContent = $content -replace "É", "&Eacute;" 
    $escapedContent = $content -replace "Ê", "&Ecirc;" 
    $escapedContent = $content -replace "Ë", "&Euml;" 
    $escapedContent = $content -replace "Î", "&Icirc;" 
    $escapedContent = $content -replace "Ï", "&Iuml;" 
    $escapedContent = $content -replace "Ô", "&Ocirc;" 
    $escapedContent = $content -replace "Œ", "&OElig;" 
    $escapedContent = $content -replace "Ù", "&Ugrave;" 
    $escapedContent = $content -replace "Û", "&Ucirc;" 
    $escapedContent = $content -replace "Ü", "&Uuml;" 
    $escapedContent = $content -replace "Ÿ", "&#376;" 
    $escapedContent = $content -replace "à", "&agrave;" 
    $escapedContent = $content -replace "â", "&acirc;" 
    $escapedContent = $content -replace "ç", "&ccedil;" 
    $escapedContent = $content -replace "è", "&egrave;" 
    $escapedContent = $content -replace "é", "&eacute;" 
    $escapedContent = $content -replace "ê", "&ecirc;" 
    $escapedContent = $content -replace "ë", "&euml;" 
    $escapedContent = $content -replace "î", "&icirc;" 
    $escapedContent = $content -replace "ï", "&iuml;" 
    $escapedContent = $content -replace "ô", "&ocirc;" 
    $escapedContent = $content -replace "œ", "&oelig;" 
    $escapedContent = $content -replace "ù", "&ugrave;" 
    $escapedContent = $content -replace "û", "&ucirc;" 
    $escapedContent = $content -replace "ü", "&uuml;" 
    $escapedContent = $content -replace "ÿ", "&yuml;" 

    # Dutch characters
    $escapedContent = $content -replace "É", "&Eacute;" 
    $escapedContent = $content -replace "Ë", "&Euml;" 
    $escapedContent = $content -replace "Ï", "&Iuml;" 
    $escapedContent = $content -replace "Ó", "&Oacute;" 
    $escapedContent = $content -replace "é", "&eacute;" 
    $escapedContent = $content -replace "ë", "&euml;" 
    $escapedContent = $content -replace "ï", "&iuml;" 
    $escapedContent = $content -replace "ó", "&oacute;"    

    $escapedContent | Set-Content $_.FullName
}
